### ISSUE TITLE
Routes are missing?

### ISSUE THREAD

**Issue by emilas44** [justinushermawan/gojek-test#1]
What about route.php file....how do you open all those views???

I can't get it to work, can you help?

**Comment by justinushermawan** [comment]
You can find it in app\Http\routes.php path.

**Comment by emilas44** [comment]
Yes i know, you have only this in routes:

```
Route::get('/', function () {
    return view('child.home');
});

Route::post('register', 'Auth\AuthController@postRegister');
```
I can't see nothing but the first page child.home
and if i fill in the form i get a white screen...no error no nothing....i think there should be more routes in routes.php???

**Comment by justinushermawan** [comment]
Yes, of course you can contact me on /justinushermawan.

**Comment by emilas44** [comment]
I have sent you a message on FB

**Comment by emilas44** [comment]
You haven't used FB a lot...do you know your password??? :)
